---
slug: :three_billion_devices_run_java
depends:
  mikutter: '3.6'
  plugin:
    - command
    - uitranslator
version: '1.2'
author: Akkiesoft
name: three_billion_devices_run_java
description: '30億のデバイスで走るJava'
